## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN', 'NAME'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
type_counts = application_df['APPLICATION_TYPE'].value_counts()
type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
type_counts.iloc[8:]

T9     156
T13     66
T12     27
T2      16
T25      3
T14      3
T29      2
T15      2
T17      1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# list of type_counts
replace_list = list(type_counts.iloc[8:].index)
replace_list

['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

In [7]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(type_counts.iloc[8:].index)
cutoff_value = 725

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Look at CLASSIFICATION value counts for binning
classification_value_counts = application_df['CLASSIFICATION'].value_counts()
classification_value_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [9]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classifications_value_cleaned = classification_value_counts.loc[classification_value_counts > 1]
classifications_value_cleaned.head(10)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
Name: CLASSIFICATION, dtype: int64

In [10]:
classification_value_counts.iloc[5:].index

Index(['C7000', 'C1700', 'C4000', 'C5000', 'C1270', 'C2700', 'C2800', 'C7100',
       'C1300', 'C1280', 'C1230', 'C1400', 'C7200', 'C2300', 'C1240', 'C8000',
       'C7120', 'C1500', 'C1800', 'C6000', 'C1250', 'C8200', 'C1238', 'C1278',
       'C1235', 'C1237', 'C7210', 'C2400', 'C1720', 'C4100', 'C1257', 'C1600',
       'C1260', 'C2710', 'C0', 'C3200', 'C1234', 'C1246', 'C1267', 'C1256',
       'C2190', 'C4200', 'C2600', 'C5200', 'C1370', 'C1248', 'C6100', 'C1820',
       'C1900', 'C1236', 'C3700', 'C2570', 'C1580', 'C1245', 'C2500', 'C1570',
       'C1283', 'C2380', 'C1732', 'C1728', 'C2170', 'C4120', 'C8210', 'C2561',
       'C4500', 'C2150'],
      dtype='object')

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_value_counts.iloc[5:].index)
cutoff_value_classifications = 1918

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [12]:
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [13]:
application_df.dtypes

APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

In [14]:
type_list = application_df.dtypes[application_df.dtypes == "object"].index.tolist()
type_list

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [15]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies = pd.get_dummies(application_df)
dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [16]:
application_df['IS_SUCCESSFUL'].values

array([1, 1, 0, ..., 0, 1, 0])

In [17]:
dummies['IS_SUCCESSFUL'].values

array([1, 1, 0, ..., 0, 1, 0])

In [18]:
# Split our preprocessed data into our features and target arrays
y = dummies['IS_SUCCESSFUL'].values
X = dummies.drop(columns='IS_SUCCESSFUL').values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [19]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [20]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
input_features_total = len(X_train[0])
hidden_nodes_layer1 = 9
hidden_nodes_layer2 = 5


nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim = input_features_total, activation = "tanh"))


# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation = "relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 9)                 396

 dense_1 (Dense)             (None, 5)                 50

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 452 (1.77 KB)
Trainable params: 452 (1.77 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [21]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [22]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6157 - accuracy: 0.6973
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5810 - accuracy: 0.7260
Epoch 3/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5636 - accuracy: 0.7277
Epoch 4/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5584 - accuracy: 0.7285
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5560 - accuracy: 0.7276
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5542 - accuracy: 0.7294
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5532 - accuracy: 0.7309
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5525 - accuracy: 0.7301
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5517 - accuracy: 0.7313
Epoch 10/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5510 - accuracy: 0.7311
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5502 - accuracy: 0.7313
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5500 - accuracy: 0.7313
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5496 - accuracy: 0.7312
Epoch 14/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5492 - accuracy: 0.7322
Epoch 15/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5488 - accuracy: 0.7318
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5485 - accuracy: 0.7319
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5480 - accuracy: 0.7320
Epoch 18/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7320
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5474 - accuracy: 0.7332
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5476 - accuracy: 0.7320
Epoch 21/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5470 - accuracy: 0.7324
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7329
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7319
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7325
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5463 - accuracy: 0.7329
Epoch 26/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5463 - accuracy: 0.7330
Epoch 27/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5461 - accuracy: 0.7339
Epoch 28/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5460 - accuracy: 0.7338
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5457 - accuracy: 0.7335
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5455 - accuracy: 0.7330
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5456 - accuracy: 0.7331
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5456 - accuracy: 0.7331
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5453 - accuracy: 0.7329
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5452 - accuracy: 0.7343
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7336
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5451 - accuracy: 0.7332
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5450 - accuracy: 0.7339
Epoch 38/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5447 - accuracy: 0.7335
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5447 - accuracy: 0.7329
Epoch 40/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5447 - accuracy: 0.7332
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5446 - accuracy: 0.7332
Epoch 42/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5446 - accuracy: 0.7332
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5445 - accuracy: 0.7331
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5445 - accuracy: 0.7342
Epoch 45/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5442 - accuracy: 0.7342
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7346
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7334
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5442 - accuracy: 0.7344
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7330
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5439 - accuracy: 0.7335
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7334
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5439 - accuracy: 0.7326
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5436 - accuracy: 0.7339
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5437 - accuracy: 0.7350
Epoch 55/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5437 - accuracy: 0.7334
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5436 - accuracy: 0.7334
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7342
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7337
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5435 - accuracy: 0.7344
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7336
Epoch 61/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5435 - accuracy: 0.7339
Epoch 62/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5433 - accuracy: 0.7350
Epoch 63/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7347
Epoch 64/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7360
Epoch 65/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5430 - accuracy: 0.7345
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7336
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7347
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7336
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7339
Epoch 70/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7334
Epoch 71/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7343
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7335
Epoch 73/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5430 - accuracy: 0.7346
Epoch 74/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7353
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7334
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7338
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7340
Epoch 78/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7348
Epoch 79/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7351
Epoch 80/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7349
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7346
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7339
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7334
Epoch 84/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7348
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7343
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7350
Epoch 87/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7354
Epoch 88/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7352
Epoch 89/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7349
Epoch 90/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7358
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7332
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7342
Epoch 93/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7345
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7357
Epoch 95/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7343
Epoch 96/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7344
Epoch 97/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7354
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7337
Epoch 99/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7347
Epoch 100/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7348

In [23]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5507 - accuracy: 0.7314 - 346ms/epoch - 1ms/step
Loss: 0.5507094264030457, Accuracy: 0.7314285635948181

In [24]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(